### ISSUE TITLE
Question: why so large counter? (42bits)

### ISSUE THREAD

**Issue by osexpert** [LiosK/uuidv7#13]
Hi. I was making my own and was thinking about a randomly seeded counter of 12, 20 or 26 bits, with +1 or a random increment. Even 12 bits with +1 would rarely rollover for me, only when the random seed is close to the max (a problem with any size random seeded counter).
 Then I saw this using  surprisingly large 42bits counter with +1. My thinking is, that a large counter  will have many bits that is unchanged when doing +1, and this will decrease the randomness /entropy?
So my thinking is, have a counter that is fully "utilized" (changes as many bits as possible) compared to how many Uuids can be made in the same ms.
But probably there is a reason here that I am not seeing,  I am guessing it can have to do with supporting time going back?
Thanks.

**Comment by osexpert** [comment]
Thanks. I see that a rust implementation also use the same/similar format as you, possibly based on your design: https://kodraus.github.io/rust/2024/06/24/uuid-v7-counters.html. How do you think this design compares to eg. Ulid's that uses all 80bits as counter? Better, worse, equal?

**Comment by LiosK** [comment]
I believe I improved ULID's 80-bit counter by ensuring a certain level of unguessability with the trailing 32-bit entropy. 32 bits won't be strong enough against offline brute-force attacks but might be practically sufficient against attacks over the network.

The counter length is smaller than ULID's, but 42 bits are already overkill for realistic use cases. Plus, the smart rollover handling using the timestamp field as a spare counter has made counter overflow a negligible event.

From the implementation standpoint, a 42-bit counter is much easier to implement because it fits in the 64-bit int/float range, than a 80-bit counter which needs BigInt arithmetics..

**Comment by osexpert** [comment]
I agree.
I am currently, in my own, using a 26bit counter and now I do not wonder anymore if I should reduce it:-) Thank you again👍
